### ISSUE TITLE
Unnecessary cookie warning

### ISSUE THREAD

**Issue by Popolechien** [openzim/openedx#113]
A cookie warning appears on top of every page even after I've clicked "ok".
![Screenshot_20200817_145951_org kiwix kiwixmobile](https://user-images.githubusercontent.com/21675885/90399103-b6855c00-e09a-11ea-872c-d709895f52bd.jpg)

**Comment by satyamtg** [comment]
This cookie is triggered by a script in the <head> of the HTML. Since all scripts and styles in the head is scraped at the moment, this pops up. I think the only way to prevent this is by using a block-list, which would be put as a parameter and would contain script names (or a unique string in the script that would be matched for inline scripts)  to prevent unnecessary scripts from loading. What do you think of it @rgaudin ? Also, the same block kist can be used to prevent the loading of the script containing a template (which seems unnecessary to me, but I'm not 100% sure), which triggers those invalid links errors.

**Comment by rgaudin** [comment]
You mean it's phzh specific? I think we should just `display: none` it via CSS and if that becomes recurrent over various instances with different selectors, create a `--hide-css-selector` option instead of blocking scripts.
