### ISSUE TITLE
Image hides text

### ISSUE THREAD

**Issue by Popolechien** [openzim/openedx#114]
On android at least, part of the navigation menu is hidden by the image:
![Screenshot_20200817_150639_org kiwix kiwixmobile](https://user-images.githubusercontent.com/21675885/90399706-ae79ec00-e09b-11ea-9ff3-88aba9655482.png)

**Comment by Popolechien** [comment]
Confirm it's a wrapping issue because on macOS with a larger screen I have no problem
![Capture d’écran 2020-08-17 à 15 12 21](https://user-images.githubusercontent.com/21675885/90399983-116b8300-e09c-11ea-831b-df1ba11b16ab.png)

**Comment by satyamtg** [comment]
@Popolechien this issue is there with the original online version as well. It uses the same CSS as the online version (though we bound it inside a container, and some little space is used on either side). However, on the online version too, with Samsung Galaxy S9 as a preset, that happens.
![Screenshot from 2020-08-17 18-58-41](https://user-images.githubusercontent.com/17774888/90401671-eabd4480-e0bb-11ea-8e90-a701ff2e0dfc.png)

**Comment by rgaudin** [comment]
Thanks @satyamtg
