### ISSUE TITLE
Error displaying content on Kiwix-JS

### ISSUE THREAD

**Issue by IPECORE** [openzim/openedx#120]
navigation is not clear and black background
![black background](https://user-images.githubusercontent.com/69838934/90515713-51e20400-e163-11ea-8d0e-ae29492eef1f.JPG)
![navigation is not clear](https://user-images.githubusercontent.com/69838934/90515717-527a9a80-e163-11ea-95f3-3125989622e6.JPG)

**Comment by satyamtg** [comment]
Okay I see. I think you're using the KiwixJS based browser extension in jQuery mode. I tried and active content doesn't work there. I get all the issues that you opened while using jQuery mode in browser extension. It appears to me that active content is not supported in browser extensions in jQuery mode. Am I right @rgaudin @kelson42 ?

**Comment by rgaudin** [comment]
Yes, @IPECORE and @Popolechien please don't use kiwix-js for testing as this is not supported/tested the same way. Let's use a shared online library for those tests. Will also prevent testing different versions of the ZIM file

**Comment by kelson42** [comment]
@rgaudin Should we move ticket to kiwix/kiwix-js?

**Comment by satyamtg** [comment]
@rgaudin @kelson42, running this on Kiwix Chrome Extension in service worker mode, it takes forever to load (probably due to large number of scripts and dynamic content). Also, loading of images and video fails with many failures logged in console.

![Screenshot from 2020-08-18 19-20-30](https://user-images.githubusercontent.com/17774888/90527134-d5651a80-e18e-11ea-96fa-b7163ea96ba0.png)

On Kiwix desktop and Kiwix-Serve though, that works fine.

**Comment by kelson42** [comment]
The problem is still visible with https://download.kiwix.org/zim/mooc/phzh_core-english-one_en_2020-08.zim. Moving to Kiwix JS.
