### ISSUE TITLE
all introduction videos must be placed correctly in the middle

### ISSUE THREAD

**Issue by IPECORE** [openzim/openedx#121]
the videos are on the left and too small, all 10
![videos_middle](https://user-images.githubusercontent.com/69838934/90619110-1f8ee000-e211-11ea-939d-084b8384bc90.JPG)

**Comment by satyamtg** [comment]
The videos are properly centered after the fix in #115. @IPECORE you can see the screenshot in that PR. Also, for the videos being small, we had a discussion regarding that in one of the issues. The point being that when we have low quality option enabled, videos would look blurred when big. That's why I fixed it to the height of the low quality preset.

@rgaudin what do you suggest in this regard?

**Comment by rgaudin** [comment]
I've updated the live demo with latest version. @IPECORE can you please take another look? As discussed in #115, this is now centered but not expanded
