### ISSUE TITLE
RTL templates not usable

### ISSUE THREAD

**Issue by Popolechien** [openzim/openedx#158]
![Capture d’écran 2020-10-20 à 08 37 20](https://user-images.githubusercontent.com/21675885/96549223-7c5d5400-12af-11eb-93a8-471df37585b2.png)

Looking at [phzh_core-arabic-one_ar](http://tmp.kiwix.org:9991/phzh_core-arabic-one_ar_2020-1), the ZIM **is not usable at all** due to UI issues:

- only videos are displayed
- rest of pages are blank
- side menu is too shrunk

@satyamtg please take a look and open sub issues if required. [zimfarm run](https://farm.openzim.org/pipeline/5f88163d937d390eedce3c4e/debug) has its log full of 404 errors.

**Comment by satyamtg** [comment]
> * only videos are displayed
> * rest of pages are blank
> * side menu is too shrunk
> 
> @satyamtg please take a look and open sub issues if required. [zimfarm run](https://farm.openzim.org/pipeline/5f88163d937d390eedce3c4e/debug) has its log full of 404 errors.

That's strange. Looks like there's an issue with the content not being scraped properly. Looking into this.

**Comment by satyamtg** [comment]
Okay, I got why we have missing content. It's because the runs for PHZH in english, arabic and german were all started at once, using the same registered e-mail ID. So, due to the nature of the scraper and openedx platform, only the connection with the latest run prevails and all other are disconnected. We can also see missing content in the english version.

This explains the presence of 404s after a certain point in the log of the arabic version.

**Comment by rgaudin** [comment]
OK, not sure how we should handle this but relaunching them all one by one

**Comment by rgaudin** [comment]
Following up on that, recipes have been updated with individual credentials and the ZIM redone. @Popolechien  the demo have been updated. I am closing this ticket.

**Comment by Popolechien** [comment]
Well the videos are not working this time around. Should I reopen a ticket or blame it on some bad run (and restart the scraper on the farm)?
