### ISSUE TITLE
Missing submit button and automatic correction after self-assessment tick boxes

### ISSUE THREAD

**Issue by Popolechien** [openzim/openedx#85]
In Topic 1 - Unit 1 - Self-evaluation it is possible to input some sort of self assessment via tick boxes and get standardized messages afterwards:
![Capture d’écran 2020-07-20 à 11 53 53](https://user-images.githubusercontent.com/21675885/87924849-bedc7e00-ca7f-11ea-9bf6-b217bb9c4bce.png)

The submit button is entirely missing and the zim only offers a meek `Warning : There is not automatic correction available for this problem.` at the top of each section instead.
![Capture d’écran 2020-07-20 à 11 52 23](https://user-images.githubusercontent.com/21675885/87925013-f5b29400-ca7f-11ea-9b68-29454589f8fa.png)

**Comment by satyamtg** [comment]
Its actually related to #27 as this info is inside hints, and the submit button is gone because the current scraping method for the problem xblock basically removes all buttons and replaces them with our own implementation (which relies on answers being present). I'm looking into ways of extracting hints for the problem xblock.
